### ISSUE TITLE
[BUG] Top-level Navigation ist weiterhin deutsch

### ISSUE THREAD

**Issue by saerdnaer** [Ultraschall/ultraschall-manual#46]
Top-level Navigation ist weiterhin deutsch, obwohl Sprache auf Englisch gestellt wurde:

<img width="1099" alt="image" src="https://github.com/Ultraschall/ultraschall-manual/assets/40266/31d5fd01-ae69-451f-a320-001307622d8a">

Wisst ihr schon woran das liegt oder soll ich mal versuchen einen PR dafür zu erstellen?

**Comment by nucleus-ffm** [comment]
Danke für das Issue. Mit der Version 5.1 haben wir die fehlende Übersetzung ergänzt. Wenn du oben rechts als Version `Next` einstellst, siehst du den aktuellen Stand der Version 5.1. Allerdings fehlen noch andere Übersetzungen in der Version 5.1, weshalb wir noch nicht umgestellt haben. Wir können mal schauen, ob wir die Übersetzung auch einfach noch in der Version 5.0 korrigieren können.

**Comment by saerdnaer** [comment]
Ich hab mal nen PR dafür geföffnet, siehe oben.

**Comment by nucleus-ffm** [comment]
Das Problem mit den Übersetzungen der Top-Level Navigation ist mittlerweile behoben. Ich schließe das issue daher mal.
